# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/trainingApp/Dockerfile'
        tags: |
          $(tag)
  
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-hub-service-connection'
        repository: 'anufrancisdocker/training-app-image'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'azure-container-registry-service-connection'
        repository: 'angularapplicationtrainingappdocker'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
      
      

    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'dockerhub-training-app'
    #     repository: 'anufrancisdocker/training-app-image'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'azure-container-registry-training-app'
    #     repository: 'angularapplicationtrainingappdocker.azurecr.io'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'